### ISSUE TITLE
Months overlapping each other

### ISSUE THREAD

**Issue by thecoorum** [computerjazz/react-native-swipe-calendar#1]
Hello and thank you for the nice lib!

## Description
I noticed a bug when sometimes on render months are overlapping each other like on the screenshot

### Update
~~As a resolution I used custom components for everything with the background the same as container background~~
Also seems like the month ago is displayed first

## Expected
Months are rendering as they should, single in view

## Media
![IMG_E849545BBC41-1](https://user-images.githubusercontent.com/32096016/152047351-a581b611-9a2f-41fd-967f-b85cb010d4b5.jpeg)

https://user-images.githubusercontent.com/32096016/152058497-09230ee5-52db-4c2a-95a8-0152e914c31e.MP4

**Comment by computerjazz** [comment]
Hm my guess is that this is a reanimated issues where initial values aren't being respected. There are several open issues around it:
- https://github.com/software-mansion/react-native-reanimated/issues/2887
- https://github.com/software-mansion/react-native-reanimated/issues/2604

What version of reanimated are you on?

**Comment by computerjazz** [comment]
ok i just pushed a workaround that hopefully fixes the race condition 🤞
can you try v `0.0.18`?

**Comment by thecoorum** [comment]
Yeah, that worked! Thanks a lot!
