### ISSUE TITLE
future of this package

### ISSUE THREAD

**Issue by Lueton** [computerjazz/react-native-swipe-calendar#4]
This is an awesome project, great work!  
  
Is there any plan to extend this project and add more features like expandable week view or marked dates and so on?  
It would be a very good alternative to [react-native-calendars](https://github.com/wix/react-native-calendars) which is for performance reasons not usable in my opinion.

Thanks!

**Comment by computerjazz** [comment]
Thanks! this package was meant to be as lean as possible -- if you want to mark dates or use other custom styles you can always roll your own `DayComponent`.

Week view is an interesting idea that I'd consider adding.

**Comment by Lueton** [comment]
That sounds great! And yes keep it lean and simple :)  
  
Unfortunately im really really new to react native so i might not be very helpful supporting this feature. I implemented a week view myself using your [react-native-infinite-pager](https://github.com/computerjazz/react-native-infinite-pager) package (works like a charm 🚀). But in terms of animating a pull down view (week <-> month) or even integrate it into your existing code is beyond my capabilities.  

heres a little [inspiration](https://wix.github.io/react-native-calendars/docs/ExpandableCalendar) for your from the package i mentioned before: 

![image](https://user-images.githubusercontent.com/42818194/183407415-3c79a5f2-c49a-44a0-bdc2-85d456c3be9b.png)

**Comment by computerjazz** [comment]
You inspired me to make some big changes in 0.0.20!
check out the different calendar modes here: https://snack.expo.dev/@computerjazz/react-native-swipe-calendar?platform=ios

**Comment by Lueton** [comment]
Awesome work! I really like it!
